### ISSUE TITLE
Cannot Open Set Black Notepad as Default Text Editor

### ISSUE THREAD

**Issue by warsponge** [savaged/BlackNotepad#13]
After several unsuccessful attempts at setting this app as my default text editor instead of the normal notepad program, I am losing hope.

I downloaded the app from the windows store and after a fair bit of searching, I found that it had saved itself into the 'Windows Apps' folder within my program files. I tried to set this app as the default by going through the standard 'open with' steps, then navigating to the folder where it is located.

This is where the first problem came up, I was told I couldn't access the files within this folder because I didn't have the correct permissions to do so, annoying and seemingly unnecessary, but a quick change to the ownership of the folder resolved this one.

Next up once I actually got to the file and selected it, I get this error message:
"Windows cannot access the specified device, path or file. You may not have the appropriate permissions to access the item"
To be clear the file I am trying to access is just an ordinary text file in my google drive folder and it opens up fine in the normal Notepad program.

To try to get around this I created a shortcut to the program, put this in a separate folder (also in my google drive), and then selected this as the program to open the files with. No luck I get the same error message as before.

So.. I then resort to just copying the entire selection of folders (4 folders within the windows apps folder in my program files) into my google drive folder, but again when I select the file, it doesn't want to play ball and I get the same error message. To add to this and just to be sure, I also went to the parent folder I had now placed the files in and changed all the ownership and permissions to my own in a hope that this would make the sufficient difference that was needed, however, unfortunately, it still didn't work.

I did download the application again here from GitHub hoping that would be a slightly different version that would allow me to use it properly however I couldn't find an executable file within this zip folder, and therefore resorted back to the windows store version.

The problem is not just limited to me not being able to set the program as my default launcher, I am literally unable to open existing files with it! The strange thing is that I can open the files if I open them from within the program through: Files ---> Open in the toolbar but obviously that's a workaround, not a solution.

Please can anyone offer some suggestions and assistance with this, I like the app and I want to work with it but I feel like I've already wasted so much of my time on something that should be very simple.

Running on Windows 10 Pro.

Thankyou in advance.

**Comment by Asibah** [comment]
Same to me

**Comment by TobyTech1234** [comment]
I'm having trouble with this too

**Comment by bluechickens** [comment]
I'm having the same issue. I really want to set this as my default windows notepad. It loses a lot of functionality by not being the default.

**Comment by rikoski** [comment]
Same to me. It loses all the purpose. I UNINSTALLED IT.

**Comment by Ponchocc** [comment]
I just went for another tool, downloaded an .exe from a webpage, as in the good old days, at this point we should not have to battle with a notepad this long... hope in the future they fix this and the print issue.

**Comment by Smartx38** [comment]
me tooo having this problem

**Comment by tempguyforblacknote** [comment]
I have figured it out. I managed to get it set up as default, but unfortunately, every time you open an already existing note, it opens up a new one. Meaning that you can't use it to open up already existing files. Sad times.

**Comment by mocky55** [comment]
I have the exact same problem.
 Funny thing is tho there's a completely different tool that's not on the Microsoft Store also called "Black NotePad". There's bunch of places to download it form. I got it at MajorGeeks.com. 
It doesn't install tho, all you download it an executable and it just opens and you're in. And it has the dark theme and I think I'm liking it. Making it default was no problem. 
I found it when I thought I could install Black NotePad from anywhere other than the Microsoft Store, cause that thing seems to be the root of all our problems xD
Maybe this helps somebody.

**Comment by asuspades** [comment]
Good to know there hasn't really been a solution yet... I won't waste my time forcing Black Notepad to set as default, but hopefully this gets resolved at some point. I need to continue using the dark theme for vision purposes, so I'll just keep opening my notes via Ctrl+O.

**Comment by eprosdev** [comment]
I found a solution; at least for me. You can drag the file from file explorer to a blank black notepad and it will open the file there. 
I use groupy so all of my notepads are tabbed together so I easily can create blank ones.

**Comment by mrlunk** [comment]
Same problem, dont waste your time on this app.

**Comment by Chispasito** [comment]
It is possible to make it the default text editor. It is a long process due to the microsoft store permissions. If you do not have admin rights, this will not be possible for you. 

I'm also making a short-story long, so bear with me. Simply put, make yourself the owner of both the WindowsApps folder and the blacknotepad app, then you change the default text app to blacknotepad. More details below:

The first thing you're going to need is permissions to access the location of Black Notepad. For me, Black Notepad's default location was in C:\Program Files\WindowsApps\55809savaged.BlackNotepad_1.0.9.0_neutral__p2aarvyam9pfc\BlackNotepad\

However, you cannot jump the gun and try to access that location because WindowsApps is a secure folder owned by the system. Let's change that

1) Unhide all folders so you can find the WindowsApps folder within Program Files
2) Right click on WindowsApps -> select properties -> go to security tab -> click advanced
3) We need to remove "system" as the owner. At the top left, select "change". You may need admin rights for this. 
4) This section will ask for an "object" to select. This means whichever people you want to have access to this must be defined. Note, I have not tried limiting this to admin. I input my personal path. I would recommend doing the same, or keeping it general at "users" 
	a) If you are unsure of what names you can enter, go to your c drive, then "users" folder and look at the names listed there. 
5) Select check names, then "ok" once it confirms your entry.
6) Another personal option here is to replace the owner on all subfolders. I did so, but it may still work without doing this step. This is because the subfolders within windowsapps don't have extra security 


Now that we have access to windowsapps, we need to change the owner on the blacknotepad app itself. 

C:\Program Files\WindowsApps\55809savaged.BlackNotepad_1.0.9.0_neutral__p2aarvyam9pfc\BlackNotepad\

1) Find the location of the blacknotepad application. For me, it was in the path listed above. But if you're hunting for it, just click on all the blacknotepad folders until you find one that says BlackNotepad. Make sure to copy your specific path as you might need it later
2) Once you get to the .exe, right-click on it, and select properties -> security tab -> advanced
3) Change the owner to your preferred profile(s)

Now that we have given ourselves the appropriate permissions, go to a .txt file -> select it -> right-click -> "Open with" -> "choose another app" -> ensure to check "always use this app to open .txt files" 

If black notepad doesn't show up on the short list, click on more apps, and then "look for another app on this pc". This will open a file explorer where you can then paste the path you copied earlier to easily find the black notepad.exe location. 

___________

This is what I remember for how to do so. If your experience is different from what I have above, please let me know so people can have the most accurate information on how to do this.

**Comment by Wolf-Schevelenbos** [comment]
I tried this, but it doesn't work. 
Black Notepad does show up now in the "Open with" menu and it even allows me to put it as a default. However, once I try opening a file I get notified I don't have the correct permissions

I changed my permissions to allow it, but it opens blank documents instead

**Comment by mrlunk** [comment]
Fuck that.
What a crap product.
Uninstall asap.
Bye now

**Comment by faycalboss** [comment]
> It is possible to make it the default text editor. It is a long process due to the microsoft store permissions. If you do not have admin rights, this will not be possible for you.
> 
> I'm also making a short-story long, so bear with me. Simply put, make yourself the owner of both the WindowsApps folder and the blacknotepad app, then you change the default text app to blacknotepad. More details below:
> 
> The first thing you're going to need is permissions to access the location of Black Notepad. For me, Black Notepad's default location was in C:\Program Files\WindowsApps\55809savaged.BlackNotepad_1.0.9.0_neutral__p2aarvyam9pfc\BlackNotepad\
> 
> However, you cannot jump the gun and try to access that location because WindowsApps is a secure folder owned by the system. Let's change that
> 
> 1. Unhide all folders so you can find the WindowsApps folder within Program Files
> 2. Right click on WindowsApps -> select properties -> go to security tab -> click advanced
> 3. We need to remove "system" as the owner. At the top left, select "change". You may need admin rights for this.
> 4. This section will ask for an "object" to select. This means whichever people you want to have access to this must be defined. Note, I have not tried limiting this to admin. I input my personal path. I would recommend doing the same, or keeping it general at "users"
>    a) If you are unsure of what names you can enter, go to your c drive, then "users" folder and look at the names listed there.
> 5. Select check names, then "ok" once it confirms your entry.
> 6. Another personal option here is to replace the owner on all subfolders. I did so, but it may still work without doing this step. This is because the subfolders within windowsapps don't have extra security
> 
> Now that we have access to windowsapps, we need to change the owner on the blacknotepad app itself.
> 
> C:\Program Files\WindowsApps\55809savaged.BlackNotepad_1.0.9.0_neutral__p2aarvyam9pfc\BlackNotepad\
> 
> 1. Find the location of the blacknotepad application. For me, it was in the path listed above. But if you're hunting for it, just click on all the blacknotepad folders until you find one that says BlackNotepad. Make sure to copy your specific path as you might need it later
> 2. Once you get to the .exe, right-click on it, and select properties -> security tab -> advanced
> 3. Change the owner to your preferred profile(s)
> 
> Now that we have given ourselves the appropriate permissions, go to a .txt file -> select it -> right-click -> "Open with" -> "choose another app" -> ensure to check "always use this app to open .txt files"
> 
> If black notepad doesn't show up on the short list, click on more apps, and then "look for another app on this pc". This will open a file explorer where you can then paste the path you copied earlier to easily find the black notepad.exe location.
> 
> This is what I remember for how to do so. If your experience is different from what I have above, please let me know so people can have the most accurate information on how to do this.

I was able to perform all the operations, but when I double-click on a text file it opens an empty page instead of opening the file in question, as if it couldn't find the path to the file. However, in the same window, when I click on Open a file, it displays the folder where the file I wanted to open previously.

**Comment by savaged** [comment]
Windows 11 now has a dark themed notepad and it has rich features. Thus it is recommended instead of this application.
